### ISSUE TITLE
New version of ace-builds not supported

### ISSUE THREAD

**Issue by arun664** [manubb/react-ace-builds#35]
# Problem

Module not found: Can't resolve 'ace-builds/src-min-noconflict/mode-bro.js' in 'C:\Users\<USERNAME&PATH>\node_modules\react-ace-builds' for the latest version of ace-builds@1.4.12

## Sample code to reproduce your issue

Just importing the module ace-builds & react-ace-builds.

import AceEditor from "react-ace-builds";
import "react-ace-builds/webpack-resolver-min.js";

## References

Documentation of react-ace-builds & Github Repo recent commits.

## Progress on:

Figured that react-ace-builds works only ace-builds@1.4.8

**Comment by manubb** [comment]
It took some times... Thanks for your report anyway.
This is fixed in version 7.3.4 (where ace-builds dep is now pinned to current last version).
